"""empty message

Revision ID: 048024497ceb
Revises: 3e7dadd1bcef
Create Date: 2022-05-17 02:19:47.220559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048024497ceb'
down_revision = '3e7dadd1bcef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('patname', sa.String(length=255), nullable=True),
    sa.Column('empid', sa.String(length=255), nullable=True),
    sa.Column('identification', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.String(length=80), nullable=True),
    sa.Column('date_scanned', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('date_scanned', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Settings')
    op.drop_table('Scans')
    op.drop_table('Results')
    # ### end Alembic commands ###
