"""empty message

Revision ID: bb11d06049d0
Revises: bb679185cca9
Create Date: 2022-05-16 03:34:02.308799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb11d06049d0'
down_revision = 'bb679185cca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('patname', sa.String(length=255), nullable=True),
    sa.Column('empid', sa.String(length=255), nullable=True),
    sa.Column('identification', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.String(length=80), nullable=True),
    sa.Column('date_scanned', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Scans')
    op.drop_table('Results')
    # ### end Alembic commands ###
